# AppVeyor is very similar to travis, with some differences to comply with
# MS Windows builds. See https://www.appveyor.com/docs/build-configuration/
# for the full documentation of the a build configuration script. See
# https://www.appveyor.com/docs/appveyor-yml/ for a complete appveyor.yml
# full syntax reference.

version: 1.0.{build}

clone_folder: c:\dev\levi

environment:
  Eigen3_DIR:          C:/Program Files (x86)/Eigen3/lib/cmake/eigen3/
  shlibpp_DIR:           C:\dev/blockfactory/build/install
  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #CMAKE_GENERATOR: "Visual Studio 14 2015"
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

init:
    # Print some more system information after installing all build tools
    - ps: echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
    - ps: echo $env:CMAKE_GENERATOR
    - ps: cmake --version
    - ps: echo "--------------------  END SYSTEM INFORMATION  --------------------"

install:

build:

build_script:
  # Build the library
  - echo "-------------------- BEGIN EIGEN INSTALLATION --------------------"
  - cd c:\dev
  - hg clone https://bitbucket.org/eigen/eigen
  - cd eigen
  - hg checkout 3.3
  - md build
  - cd build
  - cmake ..
  - cmake --build . --config Release --target INSTALL
  - echo "-------------------- BEGIN BLOCK FACTORY INSTALLATION --------------------"
  - cd c:\dev
  - git clone https://github.com/robotology/blockfactory.git
  - ps: cd c:\dev
  - ps: cd blockfactory
  - ps: md build
  - ps: cd build
  - ps: cmake -G"$env:CMAKE_GENERATOR" -DCMAKE_INSTALL_PREFIX="C:\dev/blockfactory/build/install" ..
  - ps: cmake --build . --config Release --target INSTALL
  - ps: echo "-------------------- BEGIN LEVI INSTALLATION --------------------"
  - ps: cd c:\dev\levi
  - ps: md build
  - ps: cd build
  - ps: cmake -G"$env:CMAKE_GENERATOR" -DEIGEN3_INCLUDE_DIR="C:/Program Files (x86)/Eigen3/include/eigen3" -DBUILD_TESTING:BOOL=ON -DCMAKE_CXX_FLAGS:STRING="/W4 /EHsc /bigobj" ..
  # Build the library for Release and Debug
  - ps: cmake --build . --config Debug
  - ps: cmake --build . --config Release

after_build:
  # Install only release
  #- ps: cmake --build C:\dev\lib-template-cmake\build --config Release --target INSTALL

test_script:
  - ps: ctest -C Debug -VV
  - ps: ctest -C Release -VV
